[theme]
primaryColor = "#7C3AED"
backgroundColor = "#FAFAFA"
secondaryBackgroundColor = "#C886D5"
textColor = "#7C3AED"
font = "sans serif"

[server]
enableXsrfProtection = true

[browser]
gatherUsageStats = false
