[theme]
primaryColor = "#7c3aed"
backgroundColor = "#FAFAFA"
secondaryBackgroundColor = "#FAFAFA"
textColor = "#000000"
font = "sans serif"

[server]
enableXsrfProtection = true

[browser]
gatherUsageStats = false
